apiVersion: v1
kind: List
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: frontend-hpa
    namespace: default
  spec:
    maxReplicas: 6
    minReplicas: 3
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: frontend
    targetCPUUtilizationPercentage: 80